/**
 * GitHub REST API: create repository for an implementation module.
 * Orchestrator creates repo; Modal (or implementation) pushes code.
 */

import { log } from "./logger.ts";

const GITHUB_API = "https://api.github.com";

export interface CreateRepoResult {
  cloneUrl: string;
  htmlUrl: string;
  fullName: string;
}

export async function createRepo(name: string): Promise<CreateRepoResult> {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    log.error("GITHUB_TOKEN not set");
    throw new Error("GITHUB_TOKEN required");
  }

  const safeName = name.replace(/[^a-zA-Z0-9-_]/g, "-").toLowerCase().slice(0, 100) || "epoch-app";
  const repoName = `epoch-${safeName}-${Date.now()}`;

  log.github("Creating repo " + repoName + " ...");
  const res = await fetch(`${GITHUB_API}/user/repos`, {
    method: "POST",
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      name: repoName,
      private: true,
      description: "Generated by Epoch",
      auto_init: true,
    }),
  });

  if (!res.ok) {
    const text = await res.text();
    log.error("Create repo failed: " + res.status + " " + text);
    throw new Error(`GitHub create repo failed: ${res.status}`);
  }

  const data = (await res.json()) as { clone_url?: string; html_url?: string; full_name?: string };
  const cloneUrl = data.clone_url ?? "";
  const htmlUrl = data.html_url ?? "";
  const fullName = data.full_name ?? repoName;

  log.github("Repo created: " + fullName + " " + cloneUrl);
  return { cloneUrl, htmlUrl, fullName };
}
